### ISSUE TITLE
There is a problem when pulling search domain

### ISSUE THREAD

**Issue by rosso-** [graudeejs/openvpn-update-resolv-conf-freebsd#1]
Instead of generating right resov.conf file:
```
search dnl
nameserver XX.XX.XX.XX
```
It generates such resolv.conf file:
`dnlnameserver XX.XX.XX.XX`

I don't know where is the problem, maybe it's located in resolvconf software or anywhere else. 
For now this thing is totally unusable.

**Comment by graudeejs** [comment]
@rosso- My guess is that here is the bug: https://github.com/graudeejs/openvpn-update-resolv-conf-freebsd/blob/master/update-resolv-conf.sh#L71

Change it to 
```
        R=$(printf '%s\nnameserver %s\n' "${R}" "$NS")
```
or something like that.
I don't use FreeBSD currently thus I can't test.

EDIT:
If you manage to fix it, please create Pull request.

**Comment by fsmeets** [comment]
I came across this script and created a pull request to make this work on FreeBSD https://github.com/graudeejs/openvpn-update-resolv-conf-freebsd/pull/2

**Comment by graudeejs** [comment]
#2 merged. Thanks @fsmeets
